layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Haxe
    web_url: https://haxe.org/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Haxe_logo.svg/351px-Haxe_logo.svg.png

  - name: Web design
  
  - name: JavaScript
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Unofficial_JavaScript_logo_2.svg/480px-Unofficial_JavaScript_logo_2.svg.png
    
  - name: GNU/Linux
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/407px-Tux.svg.png
    web_url: https://www.kernel.org/
  
  - name: React
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/640px-React-icon.svg.png
    web_url: https://reactjs.org/

theme: jekyll-theme-minimal